name: pack_n8n
description: "Pacote digital de recursos para criadores de conteúdo."
publish_to: 'none'
homepage: https://github.com/CostaMAyssa/pack_n8n
repository: https://github.com/CostaMAyssa/pack_n8n

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_vector_icons: ^2.0.0
  device_preview: ^1.2.0
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/image/logo.png
    - assets/
    - lib/image/image fluxos/
